version: '3'

services:
  postgresql:
    image: postgres:9.6.5
    environment:
      - POSTGRES_DB=online-store
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    ports:
      - 5434:5432